'use client';

import { useRef, useEffect, useState } from 'react';
import { useGameStore } from '@/store/gameStore';
import { buildSettlement, buildRoad } from '@/lib/api';
import {
  hexToPixel,
  getSettlementVertices,
  getHexEdges,
  drawHex,
  drawHexBorder,
  getResourceColor,
  getResourceIcon,
  isPointInHex,
  getVertexPixelCoord,
  drawSettlement,
  drawVertexMarker,
  drawRoad,
  drawNumberChip,
  isPointNearEdge,
  type HexCoord,
  type PixelCoord,
  type Vertex,
  type Edge,
} from '@/lib/hexUtils';

/** Each vertex is generated by 3 hexes; dedupe by sorted coord key. */
function dedupeVertices(vertices: Vertex[]): Vertex[] {
  const seen = new Set<string>();
  const out: Vertex[] = [];
  for (const v of vertices) {
    const key = v.hexCoords
      .map((h) => `${h.q},${h.r}`)
      .sort()
      .join('|');
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(v);
  }
  return out;
}

/** Edges are shared by 2 hexes; dedupe by unordered coord-pair key. */
function dedupeEdges(edges: Edge[]): Edge[] {
  const seen = new Set<string>();
  const out: Edge[] = [];
  for (const e of edges) {
    const key = [`${e.hex1.q},${e.hex1.r}`, `${e.hex2.q},${e.hex2.r}`].sort().join('|');
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(e);
  }
  return out;
}

type BuildMode = 'none' | 'settlement' | 'road';

interface GameBoardProps {
  gameId: string;
  buildMode?: BuildMode;
  onBuildModeChange?: (mode: BuildMode) => void;
  onActionComplete?: () => void;
}

interface HexData {
  coord: HexCoord;
  resource: string | null;
  diceNumber: number | null;
}

export default function GameBoard({ gameId, buildMode = 'none', onBuildModeChange, onActionComplete }: GameBoardProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const gameState = useGameStore();
  const [hoveredHex, setHoveredHex] = useState<HexCoord | null>(null);
  const [hoveredVertex, setHoveredVertex] = useState<Vertex | null>(null);
  const [hoveredEdge, setHoveredEdge] = useState<Edge | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Board comes from the backend (real resources + dice numbers)
  const boardHexes: HexData[] = gameState.board.map((h) => ({
    coord: { q: h.q, r: h.r },
    resource: h.resource,
    diceNumber: h.diceNumber,
  }));

  // Get all candidate vertices and edges (deduped) for hover/placement
  const allVertices = dedupeVertices(
    boardHexes.flatMap((h) => getSettlementVertices(h.coord, boardHexes.map((x) => x.coord)))
  );
  const allEdges = dedupeEdges(boardHexes.flatMap((h) => getHexEdges(h.coord)));

  const handleCanvasClick = async () => {
    if (buildMode === 'none' || loading) return;

    setLoading(true);
    setError(null);

    try {
      if (buildMode === 'settlement' && hoveredVertex) {
        await buildSettlement(gameId, hoveredVertex.hexCoords.map((h) => [h.q, h.r]));
      } else if (buildMode === 'road' && hoveredEdge) {
        await buildRoad(gameId, [hoveredEdge.hex1.q, hoveredEdge.hex1.r], [hoveredEdge.hex2.q, hoveredEdge.hex2.r]);
      } else {
        return;
      }
      setHoveredVertex(null);
      setHoveredEdge(null);
      // Keep placing during opening setup (need 2 settlements); otherwise exit build mode
      if (gameState.status !== 'setup') {
        onBuildModeChange?.('none');
      }
      onActionComplete?.();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to build');
      setTimeout(() => setError(null), 3000);
    } finally {
      setLoading(false);
    }
  };

  const handleCanvasMouseMove = (e: React.MouseEvent<HTMLCanvasElement>) => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const rect = canvas.getBoundingClientRect();
    const pixelCoord: PixelCoord = {
      x: e.clientX - rect.left,
      y: e.clientY - rect.top,
    };

    const originX = canvas.width / 2;
    const originY = canvas.height / 2;

    // In build mode, vertex/edge snapping takes priority — these sit on hex
    // corners/edges, which are *inside* hexes, so a hex-first check would
    // always win and the vertex would never register.
    if (buildMode === 'settlement') {
      // Pick the nearest vertex within range (corners are shared, so compare)
      let best: Vertex | null = null;
      let bestDist = Infinity;
      for (const vertex of allVertices) {
        const pv = getVertexPixelCoord(vertex, originX, originY);
        const d = Math.hypot(pixelCoord.x - pv.x, pixelCoord.y - pv.y);
        if (d <= 16 && d < bestDist) {
          best = vertex;
          bestDist = d;
        }
      }
      setHoveredVertex(best);
      setHoveredHex(null);
      setHoveredEdge(null);
      return;
    }

    if (buildMode === 'road') {
      let best: Edge | null = null;
      let bestDist = Infinity;
      for (const edge of allEdges) {
        const p1 = hexToPixel(edge.hex1, originX, originY);
        const p2 = hexToPixel(edge.hex2, originX, originY);
        const mid = { x: (p1.x + p2.x) / 2, y: (p1.y + p2.y) / 2 };
        const d = Math.hypot(pixelCoord.x - mid.x, pixelCoord.y - mid.y);
        if (isPointNearEdge(pixelCoord, p1, p2, 10) && d < bestDist) {
          best = edge;
          bestDist = d;
        }
      }
      setHoveredEdge(best);
      setHoveredHex(null);
      setHoveredVertex(null);
      return;
    }

    // Not building: just highlight the hovered hex
    for (const hexData of boardHexes) {
      const pixelHex = hexToPixel(hexData.coord, originX, originY);
      if (isPointInHex(pixelCoord, pixelHex)) {
        setHoveredHex(hexData.coord);
        setHoveredVertex(null);
        setHoveredEdge(null);
        return;
      }
    }

    setHoveredHex(null);
    setHoveredVertex(null);
    setHoveredEdge(null);
  };

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const rect = canvas.parentElement?.getBoundingClientRect();
    if (rect) {
      canvas.width = rect.width;
      canvas.height = rect.height;
    }

    const originX = canvas.width / 2;
    const originY = canvas.height / 2;

    // Clear canvas with a soft vertical gradient ("table")
    const bg = ctx.createLinearGradient(0, 0, 0, canvas.height);
    bg.addColorStop(0, '#0b1220');
    bg.addColorStop(1, '#0f172a');
    ctx.fillStyle = bg;
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Draw hexes with resource color, icon, and number token
    boardHexes.forEach((hexData) => {
      const c = hexToPixel(hexData.coord, originX, originY);
      const color = getResourceColor(hexData.resource);

      drawHex(ctx, c, color, '#0b1220', 2.5);

      const isHoverHex =
        buildMode === 'none' &&
        hoveredHex &&
        hoveredHex.q === hexData.coord.q &&
        hoveredHex.r === hexData.coord.r;
      if (isHoverHex) drawHexBorder(ctx, c, '#fbbf24', 3);

      // Resource icon (upper area)
      ctx.font = '19px Arial';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(getResourceIcon(hexData.resource), c.x, c.y - 16);

      // Number token (lower-center) for producing hexes
      if (hexData.diceNumber && hexData.diceNumber !== 7) {
        drawNumberChip(ctx, { x: c.x, y: c.y + 13 }, hexData.diceNumber, 15);
      }
    });

    // Faint markers on empty buildable vertices while placing
    if (buildMode === 'settlement') {
      const occupied = new Set(
        gameState.settlements.map((s) =>
          s.vertexCoords.map((v) => `${v[0]},${v[1]}`).sort().join('|')
        )
      );
      allVertices.forEach((vertex) => {
        const key = vertex.hexCoords.map((h) => `${h.q},${h.r}`).sort().join('|');
        if (occupied.has(key)) return;
        const pv = getVertexPixelCoord(vertex, originX, originY);
        drawVertexMarker(ctx, pv);
      });
    }

    // Placed roads (under settlements)
    gameState.roads.forEach((road) => {
      const p1 = hexToPixel({ q: road.hex1[0], r: road.hex1[1] }, originX, originY);
      const p2 = hexToPixel({ q: road.hex2[0], r: road.hex2[1] }, originX, originY);
      drawRoad(ctx, p1, p2, road.color, 7);
    });

    // Placed settlements
    gameState.settlements.forEach((s) => {
      const vertex: Vertex = {
        hexCoords: [
          { q: s.vertexCoords[0][0], r: s.vertexCoords[0][1] },
          { q: s.vertexCoords[1][0], r: s.vertexCoords[1][1] },
          { q: s.vertexCoords[2][0], r: s.vertexCoords[2][1] },
        ],
      };
      const pv = getVertexPixelCoord(vertex, originX, originY);
      drawSettlement(ctx, pv, s.color, 11);
    });

    // Hover preview of the spot being placed
    if (buildMode === 'settlement' && hoveredVertex) {
      const pv = getVertexPixelCoord(hoveredVertex, originX, originY);
      ctx.fillStyle = 'rgba(96, 165, 250, 0.25)';
      ctx.beginPath();
      ctx.arc(pv.x, pv.y, 16, 0, Math.PI * 2);
      ctx.fill();
      drawSettlement(ctx, pv, '#60a5fa', 12);
    }
    if (buildMode === 'road' && hoveredEdge) {
      const p1 = hexToPixel(hoveredEdge.hex1, originX, originY);
      const p2 = hexToPixel(hoveredEdge.hex2, originX, originY);
      drawRoad(ctx, p1, p2, '#60a5fa', 8);
    }

    // Lightweight build-mode hint / error (top-left)
    if (error) {
      ctx.fillStyle = '#fca5a5';
      ctx.font = 'bold 13px system-ui, sans-serif';
      ctx.textAlign = 'left';
      ctx.fillText(`⚠ ${error}`, 12, 22);
    } else if (buildMode !== 'none') {
      ctx.fillStyle = '#93c5fd';
      ctx.font = 'bold 13px system-ui, sans-serif';
      ctx.textAlign = 'left';
      ctx.fillText(
        buildMode === 'settlement' ? '🏘️ Click a corner to place' : '🛣️ Click an edge to place',
        12,
        22
      );
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [gameState.board, gameState.settlements, gameState.roads, hoveredHex, hoveredVertex, hoveredEdge, gameState.turnNumber, gameState.currentPlayerName, buildMode, loading, error]);

  return (
    <canvas
      ref={canvasRef}
      className={`w-full h-full bg-slate-950 ${buildMode !== 'none' ? 'cursor-crosshair' : 'cursor-pointer'}`}
      style={{ display: 'block' }}
      onClick={handleCanvasClick}
      onMouseMove={handleCanvasMouseMove}
      onMouseLeave={() => {
        setHoveredHex(null);
        setHoveredVertex(null);
        setHoveredEdge(null);
      }}
    />
  );
}
