'use client';

import { useRef, useEffect, useState } from 'react';
import { useGameStore } from '@/store/gameStore';
import { buildSettlement, buildRoad } from '@/lib/api';
import {
  hexToPixel,
  getSettlementVertices,
  getHexEdges,
  drawHex,
  drawHexBorder,
  getResourceColor,
  drawTextInHex,
  isPointInHex,
  getVertexPixelCoord,
  drawSettlement,
  drawRoad,
  isPointNearVertex,
  isPointNearEdge,
  type HexCoord,
  type PixelCoord,
  type Vertex,
  type Edge,
} from '@/lib/hexUtils';

/** Each vertex is generated by 3 hexes; dedupe by sorted coord key. */
function dedupeVertices(vertices: Vertex[]): Vertex[] {
  const seen = new Set<string>();
  const out: Vertex[] = [];
  for (const v of vertices) {
    const key = v.hexCoords
      .map((h) => `${h.q},${h.r}`)
      .sort()
      .join('|');
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(v);
  }
  return out;
}

/** Edges are shared by 2 hexes; dedupe by unordered coord-pair key. */
function dedupeEdges(edges: Edge[]): Edge[] {
  const seen = new Set<string>();
  const out: Edge[] = [];
  for (const e of edges) {
    const key = [`${e.hex1.q},${e.hex1.r}`, `${e.hex2.q},${e.hex2.r}`].sort().join('|');
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(e);
  }
  return out;
}

type BuildMode = 'none' | 'settlement' | 'road';

interface GameBoardProps {
  gameId: string;
  buildMode?: BuildMode;
  onBuildModeChange?: (mode: BuildMode) => void;
  onActionComplete?: () => void;
}

interface HexData {
  coord: HexCoord;
  resource: string | null;
  diceNumber: number | null;
}

export default function GameBoard({ gameId, buildMode = 'none', onBuildModeChange, onActionComplete }: GameBoardProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const gameState = useGameStore();
  const [hoveredHex, setHoveredHex] = useState<HexCoord | null>(null);
  const [hoveredVertex, setHoveredVertex] = useState<Vertex | null>(null);
  const [hoveredEdge, setHoveredEdge] = useState<Edge | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Board comes from the backend (real resources + dice numbers)
  const boardHexes: HexData[] = gameState.board.map((h) => ({
    coord: { q: h.q, r: h.r },
    resource: h.resource,
    diceNumber: h.diceNumber,
  }));

  // Get all candidate vertices and edges (deduped) for hover/placement
  const allVertices = dedupeVertices(
    boardHexes.flatMap((h) => getSettlementVertices(h.coord, boardHexes.map((x) => x.coord)))
  );
  const allEdges = dedupeEdges(boardHexes.flatMap((h) => getHexEdges(h.coord)));

  const handleCanvasClick = async () => {
    if (buildMode === 'none' || loading) return;

    setLoading(true);
    setError(null);

    try {
      if (buildMode === 'settlement' && hoveredVertex) {
        await buildSettlement(gameId, hoveredVertex.hexCoords.map((h) => [h.q, h.r]));
      } else if (buildMode === 'road' && hoveredEdge) {
        await buildRoad(gameId, [hoveredEdge.hex1.q, hoveredEdge.hex1.r], [hoveredEdge.hex2.q, hoveredEdge.hex2.r]);
      } else {
        return;
      }
      setHoveredVertex(null);
      setHoveredEdge(null);
      onBuildModeChange?.('none');
      onActionComplete?.();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to build');
      setTimeout(() => setError(null), 3000);
    } finally {
      setLoading(false);
    }
  };

  const handleCanvasMouseMove = (e: React.MouseEvent<HTMLCanvasElement>) => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const rect = canvas.getBoundingClientRect();
    const pixelCoord: PixelCoord = {
      x: e.clientX - rect.left,
      y: e.clientY - rect.top,
    };

    const originX = canvas.width / 2;
    const originY = canvas.height / 2;

    // Check hexes
    for (const hexData of boardHexes) {
      const pixelHex = hexToPixel(hexData.coord, originX, originY);
      if (isPointInHex(pixelCoord, pixelHex)) {
        setHoveredHex(hexData.coord);
        setHoveredVertex(null);
        setHoveredEdge(null);
        return;
      }
    }

    // Check vertices (settlements)
    if (buildMode === 'settlement') {
      for (const vertex of allVertices) {
        const pixelVertex = getVertexPixelCoord(vertex, originX, originY);
        if (isPointNearVertex(pixelCoord, pixelVertex)) {
          setHoveredVertex(vertex);
          setHoveredHex(null);
          setHoveredEdge(null);
          return;
        }
      }
    }

    // Check edges (roads)
    if (buildMode === 'road') {
      for (const edge of allEdges) {
        const p1 = hexToPixel(edge.hex1, originX, originY);
        const p2 = hexToPixel(edge.hex2, originX, originY);
        if (isPointNearEdge(pixelCoord, p1, p2)) {
          setHoveredEdge(edge);
          setHoveredHex(null);
          setHoveredVertex(null);
          return;
        }
      }
    }

    setHoveredHex(null);
    setHoveredVertex(null);
    setHoveredEdge(null);
  };

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const rect = canvas.parentElement?.getBoundingClientRect();
    if (rect) {
      canvas.width = rect.width;
      canvas.height = rect.height;
    }

    const originX = canvas.width / 2;
    const originY = canvas.height / 2;

    // Clear canvas
    ctx.fillStyle = '#0f172a';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Draw hexes
    boardHexes.forEach((hexData) => {
      const pixelCoord = hexToPixel(hexData.coord, originX, originY);
      const color = getResourceColor(hexData.resource);

      drawHex(ctx, pixelCoord, color, '#1e293b', 2);

      if (hoveredHex && hoveredHex.q === hexData.coord.q && hoveredHex.r === hexData.coord.r) {
        drawHexBorder(ctx, pixelCoord, '#60a5fa', 3);
      }

      if (hexData.diceNumber && hexData.diceNumber !== 7) {
        const textColor = ['wheat', 'wood'].includes(hexData.resource || '') ? '#000' : '#fff';
        drawTextInHex(ctx, hexData.diceNumber.toString(), pixelCoord, textColor, 18);
      }
    });

    // Draw placeable spots (faint) when in build mode
    if (buildMode === 'settlement') {
      allVertices.forEach((vertex) => {
        const pv = getVertexPixelCoord(vertex, originX, originY);
        ctx.fillStyle = 'rgba(148, 163, 184, 0.35)';
        ctx.beginPath();
        ctx.arc(pv.x, pv.y, 5, 0, Math.PI * 2);
        ctx.fill();
      });
    }

    // Draw placed roads (from backend) — under settlements
    gameState.roads.forEach((road) => {
      const p1 = hexToPixel({ q: road.hex1[0], r: road.hex1[1] }, originX, originY);
      const p2 = hexToPixel({ q: road.hex2[0], r: road.hex2[1] }, originX, originY);
      drawRoad(ctx, p1, p2, road.color, 6);
    });

    // Draw placed settlements (from backend)
    gameState.settlements.forEach((s) => {
      const vertex: Vertex = {
        hexCoords: [
          { q: s.vertexCoords[0][0], r: s.vertexCoords[0][1] },
          { q: s.vertexCoords[1][0], r: s.vertexCoords[1][1] },
          { q: s.vertexCoords[2][0], r: s.vertexCoords[2][1] },
        ],
      };
      const pv = getVertexPixelCoord(vertex, originX, originY);
      drawSettlement(ctx, pv, s.color, 10);
    });

    // Draw hover highlight for the spot being placed
    if (buildMode === 'settlement' && hoveredVertex) {
      const pv = getVertexPixelCoord(hoveredVertex, originX, originY);
      drawSettlement(ctx, pv, '#60a5fa', 13);
    }
    if (buildMode === 'road' && hoveredEdge) {
      const p1 = hexToPixel(hoveredEdge.hex1, originX, originY);
      const p2 = hexToPixel(hoveredEdge.hex2, originX, originY);
      drawRoad(ctx, p1, p2, '#60a5fa', 8);
    }

    // Draw title
    ctx.fillStyle = '#e2e8f0';
    ctx.font = 'bold 14px Arial';
    ctx.textAlign = 'left';
    ctx.fillText(`Turn: ${gameState.turnNumber} • ${gameState.currentPlayerName}`, 10, 20);

    if (buildMode !== 'none') {
      ctx.fillStyle = '#60a5fa';
      ctx.fillText(`Building: ${buildMode === 'settlement' ? '🏘️ Settlement' : '🛣️ Road'}`, 10, 40);
    }

    if (loading) {
      ctx.fillStyle = '#fbbf24';
      ctx.fillText('Building...', 10, 60);
    }

    if (error) {
      ctx.fillStyle = '#ef4444';
      ctx.fillText(`Error: ${error}`, 10, 60);
    }

    // Draw legend
    ctx.font = '12px Arial';
    ctx.fillStyle = '#94a3b8';
    ctx.textAlign = 'left';
    ctx.fillText('🌲 Wood  🌾 Wheat  ⛏️ Ore  🧱 Brick  🐑 Sheep', 10, canvas.height - 15);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [gameState.board, gameState.settlements, gameState.roads, hoveredHex, hoveredVertex, hoveredEdge, gameState.turnNumber, gameState.currentPlayerName, buildMode, loading, error]);

  return (
    <canvas
      ref={canvasRef}
      className={`w-full h-full bg-slate-950 ${buildMode !== 'none' ? 'cursor-crosshair' : 'cursor-pointer'}`}
      style={{ display: 'block' }}
      onClick={handleCanvasClick}
      onMouseMove={handleCanvasMouseMove}
      onMouseLeave={() => {
        setHoveredHex(null);
        setHoveredVertex(null);
        setHoveredEdge(null);
      }}
    />
  );
}
